spring.application.name=demo

spring.config.import=optional:file:src/main/resources/env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

application.file.save-directory=D:/temp_testing/

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
