spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/filedownloader
spring.datasource.username=postgres
spring.datasource.password=postgres

application.security.jwt.secret-key=lPYeEfXKqKqmbFDMIjSIadvOOFZBvgWmuPuMJWKnBWE
application.security.jwt.expiration=86400000

application.file.save-directory=D:/temp_testing/

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
