spring.application.name=demo

<<<<<<< HEAD
spring.datasource.url=jdbc:postgresql://localhost:5432/filedownloader
spring.datasource.username=postgres
spring.datasource.password=postgres
=======
spring.config.import=optional:file:src/main/resources/env.properties
>>>>>>> 9b29fcd (feat: improve download flow and secure local config)


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

application.file.save-directory=D:/temp_testing/

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
